@echo off

REM Remove files generated by compiler in this directory and all subdirectories.
REM Essential release files are kept.

echo Removing "*.csproj.user" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.csproj.user"') do del "%%i" /f /q
echo.

echo Removing "*.exe.config" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.exe.config"') do del "%%i" /f /q
echo.

echo Removing "*.vshost.exe.config" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.vshost.exe.config"') do del "%%i" /f /q
echo.

echo Removing "*.pdb" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.pdb"') do del "%%i" /f /q
echo.

echo Removing "*.vshost.application" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.vshost.application"') do del "%%i" /f /q
echo.

echo Removing "*.vshost.exe" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.vshost.exe "') do del "%%i" /f /q
echo.

echo Removing "*.vshost.exe.manifest" files...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.vshost.exe.manifest "') do del "%%i" /f /q
echo.

echo Removing "obj" directory...
rd "%~p0obj" /s /q
echo.

echo Removing "Debug" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*Debug"') do if "%%~ni"=="Debug" rd "%%i" /s /q
echo.

echo Removing "app.publish" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*app.publish"') do rd "%%i" /s /q
echo.

echo Removing "*_mcr" directories recursively...
for /f "delims==" %%i in ('dir /b /on /s "%~p0*_mcr"') do rd "%%i" /s /q
echo.

echo "%~n0.bat" done.